name: Tuto
main: com.minkang.tuto.TutoPlugin
version: 1.2.0
api-version: 1.16
commands:
  tuto:
    description: Tutorial triggers command
    usage: /tuto
    permission: tuto.admin
permissions:
  tuto.admin:
    default: op