name: UltimateRandomRoulette
main: com.minkang.ultimate.random.Main
version: 1.3.8
api-version: 1.3.8
author: MingangJeon
commands:
  random:
    description: 랜덤 룰렛 관리 명령어 (/랜덤)
    aliases: [ rr, rnd, 랜덤 ]
  package:
    description: 패키지 관리 명령어 (/패키지)
    aliases: [ pkg, 패키지 ]
    usage: "/패키지 지급 <이름> <닉네임> <갯수>"
permissions:
  ultimate.random.admin:
    description: 랜덤 룰렛 관리자 권한
    default: op
