name: TutorialWarp
version: 1.0.0
main: com.minkang.tutorial.TutorialWarpPlugin
api-version: 1.16
authors: [ "minkang" ]
commands:
  tutorial:
    description: Tutorial admin commands
    aliases: [ "튜토리얼" ]
    permission: tutorial.admin
    usage: "/tutorial sethere|remove|list|clear|reload|test"
permissions:
  tutorial.admin:
    default: op
  tutorial.bypass:
    default: op
