tutorial:
  enabled: true
  warp: tutorial   # Essentials warp name to send first-time players

finish:
  enabled: true
  # Trigger if player's feet are on any of these block types
  block-types:
    - GOLD_BLOCK
    - LIGHT_WEIGHTED_PRESSURE_PLATE
  require-sneak: false
  one-time-per-player: true
  cooldown-seconds: 2

  # Commands to run when tutorial is finished.
  # Prefixes: console:/player:/op:  (default console)
  # Placeholders: {player}, {uuid}
  commands:
    - 'console: tellraw {player} ["",{"text":"[튜토] ","color":"gold"},{"text":"튜토리얼 완료!","color":"green"}]'
    - 'console: give {player} diamond 3'
    - 'player: kits tools'
    - 'console: spawn {player}'

messages:
  already-completed: '&e이미 튜토리얼을 완료했습니다!'
  finished: '&a튜토리얼 완료! 보상이 지급되었습니다.'
  reloaded: '&aTuto 설정이 리로드되었습니다.'
  reset: '&e{player}의 튜토리얼 진행이 초기화되었습니다.'
  completed-for: '&a{player}를 완료 상태로 표시했습니다.'
