tutorial:
  enabled: true
  warp: tutorial

finish:
  enabled: true
  mode: location

  # legacy block mode (unused when mode=location)
  block-types:
    - GOLD_BLOCK

  # triggers for location mode
  triggers:
    - world: world  # stored by name; the plugin also stores world-uid for reliability
      # world-uid: 00000000-0000-0000-0000-000000000000
      x: 100
      y: 64
      z: 200
      radius: 0.0

  require-sneak: false
  one-time-per-player: true
  cooldown-seconds: 2
  # Delay to execute commands after trigger (ticks). 0 = immediate.
  execute-delay-ticks: 0

  # default commands (used if trigger has no per-trigger commands)
  commands:
    - 'console: tellraw {player} ["",{"text":"[튜토] ","color":"gold"},{"text":"튜토리얼 완료!","color":"green"}]'
    - 'console: give {player} diamond 3'
    - 'player: kits tools'
    - 'console: spawn {player}'

messages:
  finished: '&a튜토리얼 완료! 보상이 지급되었습니다.'
  reloaded: '&aTuto 설정이 리로드되었습니다.'
  reset: '&e{player}의 튜토리얼 진행이 초기화되었습니다.'
  completed-for: '&a{player}를 완료 상태로 표시했습니다.'
