tutorial:
  enabled: true
  warp: tutorial   # Essentials warp name

finish:
  enabled: true
  # mode: block | location
  mode: location

  # (mode=block) - legacy, block type based trigger
  block-types:
    - GOLD_BLOCK

  # (mode=location) - coordinates based triggers
  # Player's feet-block (integer x,y,z) must exactly match the trigger block.
  # Optional radius: if >0, uses spherical distance from (x+0.5,y+0.0,z+0.5) in blocks.
  triggers:
    - world: world
      x: 100
      y: 64
      z: 200
      radius: 0.0         # 0.0 -> exact block match
      # Optional per-trigger commands (fallback to finish.commands if omitted)
      # commands:
      #   - 'console: say {player} finished at tutorial exit'

  require-sneak: false
  one-time-per-player: true
  cooldown-seconds: 2

  # Global default commands if trigger doesn't override.
  # Prefix: console:/player:/op:
  # Placeholders: {player}, {uuid}
  commands:
    - 'console: tellraw {player} ["",{"text":"[튜토] ","color":"gold"},{"text":"튜토리얼 완료!","color":"green"}]'
    - 'console: give {player} diamond 3'
    - 'player: kits tools'
    - 'console: spawn {player}'

messages:
  finished: '&a튜토리얼 완료! 보상이 지급되었습니다.'
  reloaded: '&aTuto 설정이 리로드되었습니다.'
  reset: '&e{player}의 튜토리얼 진행이 초기화되었습니다.'
  completed-for: '&a{player}를 완료 상태로 표시했습니다.'
