name: Tuto
main: com.minkang.tuto.TutoPlugin
version: 1.0.6
api-version: 1.16
author: minkang
softdepend: [Essentials]
commands:
  tuto:
    description: Tuto admin command
    usage: /tuto <reload|reset <player>|complete <player>|status <player>|settrigger [radius]|cleartriggers|listtriggers>
    permission: tuto.admin
permissions:
  tuto.admin:
    default: op
