# .github/workflows/main.yml
name: Build Tuto (Java 8)

on:
  push: { branches: [ main, master ] }
  pull_request: { branches: [ main, master ] }
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '8'
          cache: maven

      # ✅ 루트/서브 둘 다에서 pom.xml 탐색 (target 폴더 제외)
      - name: Find pom.xml
        id: findpom
        shell: bash
        run: |
          set -e
          if [ -f "pom.xml" ]; then
            POM="pom.xml"
          else
            POM="$(find . -type f -name pom.xml -not -path '*/target/*' | head -n1 || true)"
          fi
          if [ -z "$POM" ]; then
            echo "::error::No pom.xml found in repo."
            echo "리포 구조를 확인하세요. 예: tuto/pom.xml 또는 tuto-1.0.4/tuto/pom.xml"
            exit 1
          fi
          MODULE_DIR="$(dirname "$POM")"
          echo "pom=$POM" >> "$GITHUB_OUTPUT"
          echo "module_dir=$MODULE_DIR" >> "$GITHUB_OUTPUT"
          echo "jar_glob=$MODULE_DIR/target/*.jar" >> "$GITHUB_OUTPUT"
          echo "Found POM at: $POM"

      # -f 로 정확한 POM 지정
      - name: Build with Maven
        run: mvn -q -DskipTests -f "${{ steps.findpom.outputs.pom }}" clean package

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: tuto-jar
          path: ${{ steps.findpom.outputs.jar_glob }}
          if-no-files-found: error
