name: Build Tuto (Java 11)

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Temurin JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'

      - name: Verify Java & Maven
        run: |
          java -version
          mvn -v

      - name: Build with Maven
        run: mvn -B -U -e -DskipTests package

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Tuto-jar
          path: target/*.jar
