name: Build (Java 11 preferred)

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Temurin JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'
          cache: maven

      - name: Inspect Java toolchain
        run: |
          echo "JAVA_HOME=$JAVA_HOME"
          which java || true
          java -version || true
          which javac || true
          javac -version || true

      - name: Build with Maven (prefer Java 11 profile)
        run: mvn -B -U -e -DskipTests -Pjava11plus -f "pom.xml" clean package

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: tuto-jar
          path: "**/target/*.jar"
