name: Build Tuto (Java 11)

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Temurin JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'

      - name: Verify Java & Maven
        run: |
          java -version
          mvn -v

- name: Inspect Java toolchain
  run: |
    echo "JAVA_HOME=$JAVA_HOME"
    which java || where java
    java -version
    which javac || where javac
    javac -version

- name: Build (prefer Java 11 profile)
  run: mvn -B -U -e -DskipTests -Pjava11plus clean package

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Tuto-jar
          path: target/*.jar
