# .github/workflows/main.yml
name: Build Tuto (Java 8)

on:
  push: { branches: [ main, master ] }
  pull_request: { branches: [ main, master ] }
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '8'
          cache: maven

      # 리포 안에서 pom.xml 위치 자동 탐색
      - name: Find pom.xml
        id: findpom
        shell: bash
        run: |
          set -e
          POM=$(git ls-files | grep -E '/pom\.xml$' | head -n1 || true)
          if [ -z "$POM" ]; then
            echo "No pom.xml found in repo." >&2
            echo "리포 구조를 확인하세요. 예: tuto/pom.xml 또는 tuto-1.0.4/tuto/pom.xml" >&2
            exit 1
          fi
          MODULE_DIR="$(dirname "$POM")"
          echo "pom=$POM" >> "$GITHUB_OUTPUT"
          echo "module_dir=$MODULE_DIR" >> "$GITHUB_OUTPUT"
          echo "jar_glob=$MODULE_DIR/target/*.jar" >> "$GITHUB_OUTPUT"
          echo "Found POM at: $POM"

      # POM 경로를 -f 옵션으로 지정해서 빌드 (working-directory 필요 없음)
      - name: Build with Maven
        run: mvn -q -DskipTests -f "${{ steps.findpom.outputs.pom }}" clean package

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: tuto-jar
          path: ${{ steps.findpom.outputs.jar_glob }}
